# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Syntax-Highlight-Engine-Simple-Perl-0.02

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=Syntax-Highlight-Engine-Simple-Perl&mode=dist"
SRC_URI="mirror://cpan/authors/id/J/JA/JAMADAM/Syntax-Highlight-Engine-Simple-Perl-0.02.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64 ~x86"

DEPEND=">=dev-perl/Syntax-Highlight-Engine-Simple-0.08
	virtual/perl-Module-Build
	dev-lang/perl"
