# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

EAPI=4

MODULE_AUTHOR="JWIED"

inherit perl-module

DESCRIPTION="A client for the Bugzilla web services API."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND="dev-perl/URI
	dev-perl/XML-Writer
	dev-perl/XML-Parser
	dev-lang/perl"
